### ISSUE TITLE
Addon crashes if it can't find tracked device

### ISSUE THREAD

**Issue by gurkburk76** [helto4real/hassio-add-ons#8]
[2019-09-25 22:34:13] ERROR default people_app: Device [device_tracker.pocophonef1_dn_2] does not exist!
[2019-09-25 22:34:13] ERROR default people_app: Device [device_tracker.headunit] does not exist!
panic: runtime error: index out of range
goroutine 6 [running]:
github.com/helto4real/go-daemon/daemon/defaultapps.(*PeopleApp).getHassDeviceState(0xc00014c140, 0x55c9ee3bc750, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/helto4real/go-daemon/daemon/defaultapps/people.go:273 +0x408
github.com/helto4real/go-daemon/daemon/defaultapps.(*PeopleApp).handleUpdatedDeviceForPerson(0xc00014c140, 0xc00001edc6, 0x6, 0xc00013e100)
	/go/src/github.com/helto4real/go-daemon/daemon/defaultapps/people.go:115 +0x86
github.com/helto4real/go-daemon/daemon/defaultapps.(*PeopleApp).Initialize(0xc00014c140, 0x55c9ee197a00, 0xc00009a080, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/helto4real/go-daemon/daemon/defaultapps/people.go:72 +0x1f0
github.com/helto4real/go-daemon/daemon/core.(*ApplicationDaemon).instanceAllApplications(0xc00009a080, 0x55c900000005, 0xc000132f18, 0x1)
	/go/src/github.com/helto4real/go-daemon/daemon/core/daemon.go:606 +0x69f
github.com/helto4real/go-daemon/daemon/core.(*ApplicationDaemon).loadDaemonApplications(0xc00009a080)
	/go/src/github.com/helto4real/go-daemon/daemon/core/daemon.go:542 +0x8d
github.com/helto4real/go-daemon/daemon/core.(*ApplicationDaemon).applicationDaemonLoop(0xc00009a080)
	/go/src/github.com/helto4real/go-daemon/daemon/core/daemon.go:525 +0x129
created by github.com/helto4real/go-daemon/daemon/core.(*ApplicationDaemon).Start
	/go/src/github.com/helto4real/go-daemon/daemon/core/daemon.go:87 +0x274

Seems like there was a change in how HA handles devices when restarted, they get deleted on restart until they are found again, so that's an issue for this addon :)

**Comment by helto4real** [comment]
Sorry for the late response. Did see this issue... Will check it out. Thanks for reporting.

**Comment by helto4real** [comment]
close due to no activity
